### ISSUE TITLE
Setting to select speed of animation

### ISSUE THREAD

**Issue by forteller** [Schneegans/Desktop-Cube#1]
Awesome extension. Thanks! :)

## The Motivation
The video you show of the extension is use looks great. But for some reason on my PC the animation is much faster, so I don't get to enjoy it in the same way.

## The Solution
Just a setting that lets you drag a slider to select the speed of animations would be great. Either just one slider, or one for the zoom out animation when opening the Overview and another for the spin animation when changing desktop. If two it would be nice to be able to lock them in sync.

## The Alternatives
Alternatively slow down the default speed, I guess? :)

Thanks again!

**Comment by Schneegans** [comment]
Hi there! Thanks for the suggestion!

The animations in my video clip were slower as I used Wayland's touch gestures to move the cube. I did a quick search and there seems to be indeed no other extension which modifies this transition speed. But it should be very easy to implement once we have a settings dialog. Until then, you can change the speed temporarily: Press <kbd>Alt</kbd>+<kbd>F2</kbd>, then `lg` and <kbd>Return</kbd>. In the drop-down terminal paste this:

```
imports.ui.workspacesView.WORKSPACE_SWITCH_TIME = 1000
```

The [default time is 250 ms](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/js/ui/workspacesView.js#L14). Setting it to one second (like suggested above) will make it slower until GNOME Shell is restarted!

**Comment by Schneegans** [comment]
I also found the time for entering / leaving the overview:

```
imports.ui.overview.ANIMATION_TIME = 1000
```

and for entering / leaving the app-grid state:

```
imports.ui.overviewControls.SIDE_CONTROLS_ANIMATION_TIME = 1000
```
