### ISSUE TITLE
Freezes on Pop OS

### ISSUE THREAD

**Issue by walkrr** [Schneegans/Desktop-Cube#102]
## Describe the Bug
After installing on Pop 22.04 LTS, opening the workspaces view causes the desktop to freeze. The top nav bar is still clickable but all windows and task bar disappear and the only way to fix is logging out and logging back in.

Use the workspace shortcut (Super + D) on Pop with this extension installed.

**Comment by Schneegans** [comment]
Hi there! Thanks for the report, however I think that it's a duplicate of #71, am I right?

**Comment by walkrr** [comment]
Yes it is. Apologies, I added this on mobile and when I searched that issue did not come up. Thank you
