### ISSUE TITLE
Cube only shows on secondary monitor

### ISSUE THREAD

**Issue by Policepigeon** [Schneegans/Desktop-Cube#110]
If I have two monitors set up in extend config, and I turn the cube on, the cube only shows on the secondary monitor

Ubuntu 22.04 lts, gnome x11, version 42.5, desktop cube 13

**Comment by Schneegans** [comment]
Hey there, thanks for the report! Could you please provide some more information:
* The cube should show up on all monitors which have workspaces enabled. Have you multiple workspaces on all monitors?
* Have you tried disabling all other extensions?

**Comment by Policepigeon** [comment]
I disabled all extensions individually, and it is an incompatibility with the User Themes extension.

**Comment by Policepigeon** [comment]
Thanks for the help, love your extensions.
