### ISSUE TITLE
Show workspace names

### ISSUE THREAD

**Issue by AJCxZ0** [Schneegans/Desktop-Cube#111]
## The Motivation
Through so well hidden in GNOME, workspaces still have names as they have since time (and window managers) immemorial. It would be nice to actually see them.
```
$ gsettings describe org.gnome.desktop.wm.preferences workspace-names
Defines the names that should be assigned to workspaces. If the list is too long
for the current number of workspaces, names in excess will be ignored. If the
list is too short, or includes empty names, missing values will be replaced with
the default (“Workspace N”).
```

## The Solution
Display workspace names on or above the workspace in the cube, optionally zooming, enlarging, highlighting and/or otherwise emphasizing the name of the currently displayed workspace.
Provide configuration settings for position, size, font, background, opacity, etc. with sensible defaults which fit reasonable names without significantly obscuring workspace content.

## The Alternatives
Display the workspace name briefly upon selection as an overlay.
Provide configuration settings for duration, position, size, font, background, opacity, etc. with sensible defaults which fit reasonable names on the screen.

**Comment by Schneegans** [comment]
Hey there! Thanks for the suggestion. While this could be possible, I am not sure if it's really in the scope of the Desktop Cube extension. Maybe it should rather be an extension on its own?

On Fedora, there is the Background Logo extension (https://fostips.com/custom-background-logo-fedora/) which overlays a custom image over the wallpaper, which is not only shown in desktop mode but also in the overview. Maybe a similar approach could be used to show the workspace name on each wallpaper.

What do you think?

**Comment by AJCxZ0** [comment]
No objection to this function belonging elsewhere.

**Comment by Schneegans** [comment]
I think that this is a good idea for an extension, though. Maybe you could ask in the extensions matrix channel whether someone would be interested in developing something like that. Usually, there are plenty of extension developers around!

**Comment by AJCxZ0** [comment]
[Done](https://matrix.to/#/!FYdkgfOfvxTEwepUJb:gnome.org/$J08HkIQQRe9kOnp3nnCXmVhRzZrp4ElEPxi-EvSrl3s). Thank you for the suggestion.
