### ISSUE TITLE
Screens offset when using Vertical Overview

### ISSUE THREAD

**Issue by smurfix** [Schneegans/Desktop-Cube#121]
## Describe the Bug
Restoring Gnome's old vertical overview confuses Cube.

1. Install + enable the Vertical Overview extension.
2. Drag on the desktop.

## Observed Behavior
The workspaces are now offset vertically, i.e. the top left corner of workspace #2 is now adjacent to the bottom right corner of workspace #1 instead of the top right corner.

## Expected Behavior
No change.

## System
_Please complete the following information:_
 - Linux distribution: Debian Testing
 - Desktop Cube version: DL from gnome on 2023-04-13
 - GNOME Shell version: 44

**Comment by Schneegans** [comment]
Hi there! Thanks for the report. However, this is a duplicate of #71. I just changed the title of #71 to make it easier to find for others in the future. If you have any suggestions, please report them in #71.
