### ISSUE TITLE
Causes all extensions to be disabled on login, even though works after re-enabling, on GNOME 44

### ISSUE THREAD

**Issue by tjyrinki** [Schneegans/Desktop-Cube#123]
## Describe the Bug

Currently every time I login to GNOME 44, I first get back to login screen, and then can login but with extensions disabled. I can however re-enable the extensions and also Desktop Cube works fine.

I now pinpointed it to this particular extension. That is, with all others enabled but Desktop Cube disabled, I can login without extensions getting disabled. If I have Desktop Cube enabled upon logout, the next login will again cause fallback back to gdm and login possible only with all extensions disabled.

This is new behavior on GNOME 44, so possibly something triggering GNOME's error detection on startup only. (on an earlier GNOME version I had a similar problem with another extension, [this commit](https://github.com/rcaelers/workrave/commit/56af818cd3e148069134551aacc7b06043d8541a) fixed it over there).

```
journalctl -f -o cat | grep -E 'desktop-cube|':
[ERROR glean_core] Error setting metrics feature config: Json(Error("EOF while parsing a value", line: 1, column: 0))
[session uid=1000 pid=15888] Activating service name='org.gnome.BrowserConnector' requested by ':1.90' (uid=1000 pid=17792 comm="/usr/bin/python3 /usr/bin/gnome-browser-connector-")
[session uid=1000 pid=15888] Successfully activated service 'org.gnome.BrowserConnector'
Window manager warning: Ping serial 868769 was reused for window W4, previous use was for window W3.
[session uid=1000 pid=15888] Activating via systemd: service name='org.gtk.vfs.Metadata' unit='gvfs-metadata.service' requested by ':1.13' (uid=1000 pid=16385 comm="/usr/bin/gnome-shell")
Starting Virtual filesystem metadata service...
[session uid=1000 pid=15888] Successfully activated service 'org.gtk.vfs.Metadata'
Started Virtual filesystem metadata service.
Starting Cleanup of User's Temporary Files and Directories...
Finished Cleanup of User's Temporary Files and Directories.
```

## Expected Behavior
Login works normally with Desktop Cube enabled.

## System
 - OS: openSUSE Tumbleweed 20230413
 - Desktop Cube version: 15
 - GNOME Shell version: 44.0

**Comment by Schneegans** [comment]
Hi there! Thanks for the report. Currently, I cannot reproduce this in a virtual machine. What happens if you run a nested GNOME Shell session (`dbus-run-session -- gnome-shell --nested --wayland`)? Does it open properly or does it somehow fail?

**Comment by tjyrinki** [comment]
I tried with ```env GNOME_SHELL_SLOWDOWN_FACTOR=2 MUTTER_DEBUG_DUMMY_MODE_SPECS=1024x768 dbus-run-session -- gnome-shell --nested --wayland```

It seems good as a way to test, as without Desktop Cube the nested shell starts, but with Desktop Cube enabled it fails to start. Now the only problem is to find meaningful snippets in the logs. There are clearly a lot of these when cube is enabled:
```(/usr/libexec/xdg-desktop-portal:24670): GLib-GIO-CRITICAL **: 18:49:44.189: Error while sending AddMatch() message: The connection is closed``` (and the same message for ```(org.gnome.Nautilus:24654)```). And before those also these are unique to the "failing" log: ```(evolution-addressbook-factory:24617): libedbus-private-WARNING **: 18:49:44.183: Error setting property 'ConnectionStatus' on interface org.gnome.evolution.dataserver.Source```. And ```Gdk-Message: 18:49:44.182: Error reading events from display```. Plus ```(/usr/libexec/xdg-desktop-portal:24670): GLib-WARNING **: 18:49:44.190: GError set over the top of a previous GError or uninitialized memory. This indicates a bug in someone's code. You must ensure an error is NULL before it's set.```

All in all I don't see anything directly indicating the extension, just that something fails which then kills the starting of the shell and the rest of the services fail alongside it.

**Comment by Schneegans** [comment]
By now, I also updated my system to GNOME 44, but I cannot reproduce this. I would suggest to run nested GNOME Shell once with the extension and once without and compare the output using `diff`. Maybe you can spot something?

**Comment by tjyrinki** [comment]
My previous comment was exactly that, sorry if I explained it poorly :) The error messages mentioned were such that only appeared in the output when the extension was enabled and also lead to the failing of starting the nested shell. As mentioned, there was nothing directly telling what's going wrong, but a lot more errors in general.

**Comment by pnickerson-cashstar** [comment]
To help with reproduction: Try setting the background panorama. Specifically, I experience an issue similar to this when I use J&E Gray 02 HDRI from [https://polyhaven.com/a/je_gray_02](https://polyhaven.com/a/je_gray_02), the "8K Tonemapped JPG • 60.61 MB" download.
File name: `je_gray_02.jpg`
md5sum: `82884fa69ddaedcd0af5b159523da16a`

I'm not sure if my issue is identical, though. I'm using X11 (not Wayland) on Fedora Linux 38 (Workstation Edition). If I have Desktop Cube enabled and I've got that image as my background panorama, then when I start up my laptop and log in, GNOME appears to keep crashing and restarting. If I reboot and I'm lucky, all extensions have been disabled and I can log in and reenable them all.

Or, while GNOME is in the crash loop, I can hit Ctrl + Alt + F3, log in, run `gsettings set org.gnome.shell disable-user-extensions true`, and hit Alt + F2.

**Comment by tjyrinki** [comment]
@pnickerson-cashstar Good point, if I disable my background picture (self-taken 8704 × 4352 360 degree panorama picture) it doesn't crash anymore even on GNOME 44.

**Comment by Schneegans** [comment]
Great that you discovered that it's related to the panorama. However, I cannot reproduce this - neither on X11 nor on Wayland. Does lowering the resolution help? What kind of GPU do you have?

**Comment by tjyrinki** [comment]
Mine is Intel® Xe Graphics (TGL GT2).

Downscaling to 4096x2048 worked, although now the image is indeed blurry. And it's not that the higher resolution (8704x4352) doesn't work, it loads fine on second try and the desktop is stable in even long term use.

Attached is a pure white 8704x4352 pixel jpg with which I can reproduce the problem easily.
![white-8704x4352](https://user-images.githubusercontent.com/1052406/236666763-300939cb-16f2-442b-b0c3-1a5648c81250.jpg)

**Comment by Schneegans** [comment]
As I said before, this does not happen on my end. However, I just pushed a change to a separate branch which makes the skybox texture loading asynchronous. May this helps? You can test it as follows:

```
git clone https://github.com/Schneegans/Desktop-Cube.git
cd Desktop-Cube
git checkout feature/async-panorama
make install
```

Then restart GNOME Shell with <kbd>Alt</kbd> + <kbd>F2</kbd>, <kbd>r</kbd> + <kbd>Enter</kbd>.
Or logout / login if you are on Wayland.

**Comment by tjyrinki** [comment]
"Interesting". In my quick testing, for whatever reason, it seems to fix launching nested GNOME Shell with the big texture - it works fine - but _still_ crashing the real desktop session upon startup once (so I need to lanch Extensions and enable extensions - which then loads all of them fine). I tried also rebooting and the results seem consistent.

To be exact, I tested with
```
cd .local/share/gnome-shell/extensions/desktop-cube@schneegans.github.com/
wget 'https://github.com/Schneegans/Desktop-Cube/commit/b465f3443f8c364f5666ea40d468d57b3653da3e.patch' -O skybox.patch
patch -p1 < skybox.patch
```

**Comment by Schneegans** [comment]
Weird. Are you 100% sure that the patch is still applied? The gnome-extensions app occasionally re-downloads the extension from extensions.gnome.org and overwrites any local modifications. To ensure that this does not happen, you have to increase the version number in the `.local/share/gnome-shell/extensions/desktop-cube@schneegans.github.com/metadata.json`.

Else this will be pretty hard to debug. You could try to scatter some `utils.debug("some message");` into the `Skybox.js` and see if they get logged to journalctl. For instance [here](https://github.com/Schneegans/Desktop-Cube/blob/feature/async-panorama/src/Skybox.js#L46) or [here](https://github.com/Schneegans/Desktop-Cube/blob/feature/async-panorama/src/Skybox.js#L129). Maybe we can find the place where it crashes.

**Comment by tjyrinki** [comment]
I'm 100% sure and continue to reproduce "works in nested shell" vs "doesn't work on real gnome-shell login but works when re-enabling extensions after login".

All in all it looks like the texture loading goes ok, but somehow when it fails it doesn't get to vfunc_paint_target(node, paintContext)

I'm not sure of the codeflow and asynchronousity, but in my thrown out debugging messages in the failing case it does get this.queue_repaint(); done but that's the last of it, while in the working case it executes vfunc_paint_target(node, paintContext) { and everything within it.

You can check the Skybox.js I'm using and how the logging goes (in reverse chronological order) at https://people.debian.org/~timo/desktop-cube/

**Comment by dkopko** [comment]
I am another user also experiencing the same issue.

**Comment by Schneegans** [comment]
Can anybody still reproduce this issue? For GNOME 45, I refactored the Skybox code quite a lot. Maybe it got fixed along the way?

**Comment by dkopko** [comment]
I'll give it a try after Fedora 39 is out of beta and report back.  Thank you!

**Comment by tjyrinki** [comment]
openSUSE Tumbleweed, GNOME 45, working great now! I'm using the original 8704x4352px Pixel photosphere background again, and have both logged out / re-logged in and rebooted without issues with extension(s). Thank you a lot!

**Comment by Schneegans** [comment]
Awesome! It's neat if bugs are fixed along the way :wink:
