### ISSUE TITLE
The README.MD mentions and refers to "compiz-alike window effects" but the page does not exist on gnomes site

### ISSUE THREAD

**Issue by claudiusraphael** [Schneegans/Desktop-Cube#131]
## Describe the Bug
![image](https://github.com/Schneegans/Desktop-Cube/assets/84972255/4e008d54-6826-4092-b28a-16fac327499c)

![image](https://github.com/Schneegans/Desktop-Cube/assets/84972255/cdbe82f8-68cb-4bfa-8861-cf2d19c5f150)

**Comment by Schneegans** [comment]
Thanks for the hint! I just fixed it.
