### ISSUE TITLE
Often rotates 2 or more workspaces when rotated only 1 workspace

### ISSUE THREAD

**Issue by caedmon-kitty** [Schneegans/Desktop-Cube#135]
## Describe the Bug
Using click on the desktop and drag on the desktop I rotate 1/2to 3/4 the way to the next desktop.  More often than not the rotation is 2 or more workspaces.  It is nearly impossible to rotate a single workspace.

1. click and drag on the desktop (either direction) 1/2 - 3/4 of a workspace.
2. release the left mouse button.
3. More often than not the rotate goes 2 or more workspaces in the direction of the drag.
4.  It is not possible to determine how many workspaces it will rotate.
5. 

journalctl -f -o cat | grep -E 'desktop-cube|' showed no errors related  to desktop-cube

## Expected Behavior
rotation should stop on the workspace currently displayed

## System
_Please complete the following information:_
 - Linux distribution: ubuntu 22.04
 - Desktop Cube version: desktop-cubeschneegans.github.com.v17.shell-extension.zip
 - GNOME Shell version: 42.9-0ubuntu2

**Comment by Schneegans** [comment]
Hi there! Thanks for the report. This is an issue I wanted to look into for quite some time now. I think I found at least a partial solution.

The `SwipeTrackers` in GNOME Shell seem to ignore the time between the last pointer movement and the mouse button release when computing the velocity for the workspace movement. So if you make a rather quick movement with your pointer while dragging the cube, then stop for some time before releasing the mouse button, the cube will continue spinning as if you hadn't stopped. If you want to, you could test the code in #136! This should fix this issue.

However, one issue remains: For my liking, the computed velocity at which the cube spins after rotating with the mouse is still too high. But I think there's not much we can do about this. This is controlled with pretty hard-coded values in GNOME shell.
