### ISSUE TITLE
Wrap around the cube

### ISSUE THREAD

**Issue by castrojo** [Schneegans/Desktop-Cube#14]
## The Motivation
It'd be nice to wrap around the cube when you get to the last workspace. There is an extension that allows for this to happen, however if you try it it kind of turns the cube all the way back to workspace 1 from 4 instead of just moving one over from 4 to 1. 

Extension I'm talking about is here: https://extensions.gnome.org/extension/1116/workspace-switch-wraparound/

## The Solution
It'd be nice if there was just a wraparound function that "kept going" in the direction I'm going in. Not sure if this should live in desktop-cube or the wrap around extension but I figure I'd ask here first.

**Comment by Schneegans** [comment]
This would be nice indeed. However, it will be pretty hard to implement, I guess. There are many components of the shell which visualize the current workspace (e.g. the minimap in the overview or the workspace-switcher overlay). All of them have would have to be tweaked to deal with this new behavior...

Nevertheless, I'll see if it is possible :)

**Comment by castrojo** [comment]
Ah, that's probably not worth the investment, the more you touch the harder upgrades will be to maintain. Maybe someday!
