### ISSUE TITLE
Updated libcue2:amd64 this morning, now the Cube gets only half way, and needs another swipe to complete the rotation

### ISSUE THREAD

**Issue by vescovaccio** [Schneegans/Desktop-Cube#140]
The Cube gets stuck half rotated on swipe and needs another swipe to change face of the cube. It doesn't snap into place. The same is true when swiping down to get to the overview. It took one quick swipe before and now takes several. If the desktop or overview isn't perfectly lined up, I can't use any windows. Only thing different about my system today is that the package libcue2:amd64 got updated. Don't know whether this is the culprit or not. I am on Standard Ubuntu 22.04.3, Gnome 42.9, X11 session, using the X11gestures extension by X11gestures@joseexposito.github.io as always. When I get disable X11gestures, the Cube starts working again. But I lose the gestures - the three-finger swipe left or right becomes a four-fingered (hit or miss on my track pad) up or down (to rotate the Cube left or right). The 3-finger swipe down to enter the overview becomes a four-fingered swipe right.

Unfortunately, between the Cube and X11 gestures, I have to choose X11 gestures. It's a shame that from today they don't work together. I have used Desktop-Cube (together with X11gestures) for years now, and love it. Thank you so much! But right now it simply isn't usable.

:-(

**Comment by in4matix** [comment]
I am also on Ubuntu 22.04.3 and I use Gesture Improvements by harshadgavali with Desktop Cube (Awesome Extension) but on Wayland and I have no issues. Not sure if it is a possible solution for you...

**Comment by vescovaccio** [comment]
For the moment I'm stuck on X, because I use a Java app that has fuzzy text on Wayland, with fractional scaling, and an Nvidia graphics card, with the proprietary driver. Hoping to move to Wayland, but not there yet. Thanks! I'll check out Gesture Improvements by harshadgavali.

**Comment by Schneegans** [comment]
Hi there! Thanks for the report. Maybe that's a regression introduced with the latest version? Could you try installing the previous version and check if this solves the issue?

You can get it from [here](https://github.com/Schneegans/Desktop-Cube/releases/tag/v19) and install it with `gnome-extensions install <zip file>`. It may auto-update again to the latest version - to prevent this, you can simply set the version number in `~/.local/share/gnome-shell/extensions/desktop-cube@schneegans.github.com/metadata.json` to a large number.

**Comment by vescovaccio** [comment]
Hi Simon, I installed the previous version 19 as instructed (gnome-extensions install desktop-cube@schneegans.github.com.zip, using the zip packaged you linked to), modified the version number (nano ~/.local/share/gnome-shell/extensions/desktop-cube@schneegans.github.com/metadata.json) from 19 to 25, therefore above the current number 20, then logged out and back in, and, unfortunately, I am unable to enable the extension, either in the Extension Manager app or the Extensions app, which says "The extension is incompatible with the current GNOME version". Is there a way to override this and force enabling the extension?

**Comment by Schneegans** [comment]
Ahh, sorry, version 19 was for GNOME 45 already. I think the last-but-one version for pre-GNOME 45 was version 17. Could you try that one?

**Comment by vescovaccio** [comment]
Ah, ok. I can confirm that version 17 works perfectly as expected, both with and without X11gestures enabled. So, maybe you are right that it's a regression introduced with the latest version. 17 works, but 20 doesn't. I'll follow this issue to see whether you are able to hunt down the regression, and waiting on a fix, I'll stay on 17, or disable for now. Many thanks Simon!

**Comment by vescovaccio** [comment]
Yes, certainly, my GitHub isn't a shinning example, but go ahead! Good luck with the solution, and thanks for everything!

**Comment by Schneegans** [comment]
You are now on the list :smile:. If you want another link, just let me know.

I think that I have found the issue. It may actually be a [bug in X11 gestures](https://github.com/JoseExposito/gnome-shell-extension-x11gestures/pull/53).

**Comment by vescovaccio** [comment]
Thanks, let's hope José can fix it without any problems!

**Comment by Schneegans** [comment]
@JoseExposito merged the fix, so it will be included in the next version of X11Gestures. So I guess we can close this issue here. Thanks again for reporting it!

**Comment by vescovaccio** [comment]
Perfect, thanks Simon! A pleasure to be able to help in some small way, and to continue using the Cube! And X11gestures!
