### ISSUE TITLE
My desktop icons disappear when I change the workspace by dragging.

### ISSUE THREAD

**Issue by rznkolds** [Schneegans/Desktop-Cube#142]
I'm using Gnome 44.5 on Fedora, and no matter which desktop icon plugin I use, the icons disappear whenever I change the workspace with mouse drag.

A small video as an example :

[sender.webm](https://github.com/Schneegans/Desktop-Cube/assets/97980164/9349a67e-a430-423b-8b66-be2fc698b220)

---

The only system output is these :

231015 13:39:36.862 connection:506 ▶ WARN 581 network: failed to get process and profile of PID 2711: process does not exist
clutter_actor_insert_child_below: assertion 'sibling == NULL || (CLUTTER_IS_ACTOR (sibling) && sibling->priv->parent == self)' failed
clutter_actor_insert_child_below: assertion 'sibling == NULL || (CLUTTER_IS_ACTOR (sibling) && sibling->priv->parent == self)' failed
clutter_actor_insert_child_below: assertion 'sibling == NULL || (CLUTTER_IS_ACTOR (sibling) && sibling->priv->parent == self)' failed
clutter_actor_insert_child_below: assertion 'sibling == NULL || (CLUTTER_IS_ACTOR (sibling) && sibling->priv->parent == self)' failed
231015 13:39:41.777 connection:506 ▶ WARN 583 network: failed to get process and profile of PID 2711: process does not exist
clutter_actor_insert_child_below: assertion 'sibling == NULL || (CLUTTER_IS_ACTOR (sibling) && sibling->priv->parent == self)' failed
clutter_actor_insert_child_below: assertion 'sibling == NULL || (CLUTTER_IS_ACTOR (sibling) && sibling->priv->parent == self)' failed
clutter_actor_insert_child_below: assertion 'sibling == NULL || (CLUTTER_IS_ACTOR (sibling) && sibling->priv->parent == self)' failed
clutter_actor_insert_child_below: assertion 'sibling == NULL || (CLUTTER_IS_ACTOR (sibling) && sibling->priv->parent == self)' failed
clutter_actor_insert_child_below: assertion 'sibling == NULL || (CLUTTER_IS_ACTOR (sibling) && sibling->priv->parent == self)' failed
clutter_actor_insert_child_below: assertion 'sibling == NULL || (CLUTTER_IS_ACTOR (sibling) && sibling->priv->parent == self)' failed
clutter_actor_insert_child_below: assertion 'sibling == NULL || (CLUTTER_IS_ACTOR (sibling) && sibling->priv->parent == self)' failed
clutter_actor_insert_child_below: assertion 'sibling == NULL || (CLUTTER_IS_ACTOR (sibling) && sibling->priv->parent == self)' failed
231015 13:39:46.795 connection:506 ▶ WARN 585 network: failed to get process and profile of PID 2711: process does not exist
231015 13:39:51.809 connection:506 ▶ WARN 587 network: failed to get process and profile of PID 2711: process does not exist

----

After dragging the cube, the icons should be visible, but when you change it via the workspace indicator, the icons appear again.

---

 - Linux distribution : Fedora 38
 - Desktop Cube version : 21
 - GNOME Shell version: 44.5

**Comment by Schneegans** [comment]
Hi there! Thanks for the report. Has this been working for you on a previous version? Or is this the first time you try to use both extensions together?

**Comment by rznkolds** [comment]
This is the first time I'm using both extensions together.

**Comment by Schneegans** [comment]
Well, I cannot really reproduce this on my end. I am on GNOME 44.3 currently.

* If I use [Desktop Icons NG (DING)](https://extensions.gnome.org/extension/2087/desktop-icons-ng-ding/), the icons disappear during rotations but re-appear once the rotation is done.
* With [Gtk4 Desktop Icons NG (DING)](https://extensions.gnome.org/extension/5263/gtk4-desktop-icons-ng-ding/) the icons stay visible even during rotations.

Which extension are you using? And could you please disable all other extensions except for the Desktop Cube and the Desktop Icons extension?

**Comment by rznkolds** [comment]
I found the problem, it was doing such a thing because of the blur my shell plugin.

It might be better if I let them know the situation :)
