### ISSUE TITLE
missing features

### ISSUE THREAD

**Issue by speefak** [Schneegans/Desktop-Cube#149]
It would be great if i can switch all desktops around. Actually i can switch to last desktop and if i want to switch to the first desktop i have to rotate 9 other Desktops ( i use 10 Desktops, fixed ). And if you put the overview to right screen edge like gnome 3.3 or the vertical overview extension.

Remembering @ Beryl in approx. 2010. This was the best Desktop i ever used. Hope the Desktop Cube get over the time similar features ;)

thx for plugin ;)

**Comment by Schneegans** [comment]
Hey thanks for the request. However, this is aduplicate of #122 😉
