### ISSUE TITLE
Conky theme disappear after use cobe effect.

### ISSUE THREAD

**Issue by MarsSwimmer** [Schneegans/Desktop-Cube#159]
## Describe the Bug

Conky theme disappear after use cobe effect.

1. conky theme execute at startup.
2. Desktop cube extesion is turn on.
3. click and drag desktop, it show 3d cube effect, when back to desktop, conky theme disappear, cant show anymore, but the conky progress is still alive.

## Expected Behavior
I hope author can fix this bug, when 3d effect finish, back to desktop, conky theme show again.

## System
_Please complete the following information:_
 - Linux distribution [e.g. Ubuntu 23.10]
 - Desktop Cube version 22 (get from metadata.json)
 - GNOME Shell version: 45

**Comment by MarsSwimmer** [comment]
this is video record

https://github.com/Schneegans/Desktop-Cube/assets/146618222/9fa511fc-52e7-440f-8bae-f2eb080f776d

**Comment by MarsSwimmer** [comment]
I'm sorry, I find this problem is not desk cube's bussiness, it cause blur my shell conflict with desktop cube, the problem show when blur application on.

I should close this issue, thanks.

**Comment by ichristophe56** [comment]
vu
