### ISSUE TITLE
Cube crashes my desktop when I toggle it on.

### ISSUE THREAD

**Issue by Slot2995** [Schneegans/Desktop-Cube#162]
Everytime I enable extensions my whole GNOME session goes black then signs out, when I log back in I get pushed out again, login again to the extensions being turned off to

OS: Arch Linux x86_64
Host: ThinkPad T560
Kernel: 6.8.2-arch1-1
Uptime: 6 hours, 4 mins
Packages: 909 (pacman), 19 (flatpak)
Shell: bash 5.2.26
Resolution: 1920x1080
DE: GNOME 46.0
WM: Mutter
WM Theme: Adwaita
Theme: Adwaita-dark [GTK2/3]
Icons: Adwaita [GTK2/3]
Terminal: kgx
CPU: Intel i7-6600U (4) @ 3.400GHz
GPU: NVIDIA GeForce 940MX
GPU: Intel Skylake GT2 [HD Graphics 520]
Mmory: 3125MiB / 15853MiB

I was able to switch over to GNOME 46 without any issues but the following update this started happening. there were some extensions that were unsupported after the update so I uninstalled them but still having the same issue every time turn on the extensions

**Comment by Schneegans** [comment]
Hi there! Have you disabled all other extensions to make sure that this is really an issue with the Desktop Cube and not maybe an incompatibility with another extension?

**Comment by Slot2995** [comment]
yes I actually sent this issue to all the wrong people first. but someone from the GNOME shell team explained how to check them all one at a time. I have had some other issues with the desktop cube in the past so it was one of the first that I checked. I obviously don't know a lot about how to check every detail of the problem so if you need any other info or have any suggestions I could try let me know.

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by Schneegans** [comment]
I just installed Fedora 40 in a VM with GNOME Shell 46.0. I tested the extension with X11 and Wayland and I do not experience any issues. Have you really tried this with _all_ extensions disabled? Like disable all, reboot, enable the cube?

You could explore the logs since the last boot with `journalctl -b -e -o cat`. Is there anything in there which mentions "gjs", "extensions",  or "desktop-cube"?

**Comment by Neo-29** [comment]
There's something going on at the moment with lock and /or suspend breaking extensions.
I have the same issue not only with desktop cube but with gestures broken (only switching desktop)

Could be linked to a parameter in some  extensions causing this.

**Comment by Neo-29** [comment]
> I just installed Fedora 40 in a VM with GNOME Shell 46.0. I tested the extension with X11 and Wayland and I do not experience any issues. Have you really tried this with _all_ extensions disabled? Like disable all, reboot, enable the cube?
> 
> You could explore the logs since the last boot with `journalctl -b -e -o cat`. Is there anything in there which mentions "gjs", "extensions", or "desktop-cube"?

The problem is that it can occur with any other extension on.

Really hard to debug.

**Comment by Slot2995** [comment]
Yes, just to be sure I tried it again disabled all of the extensions reinstalled the desktop cube and my shell crashed the second I did. I don't see anything in that output that specified any of what you mentioned, but again I don't exactly know what I am looking at or for. I could send you the output but I don't really want to post all of it on a public message board.

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by Neo-29** [comment]
Confirmed

**Comment by Schneegans** [comment]
Please make sure not to confuse the issues. If I got it right, @Slot2995 is talking about the Shell crashing when enabling the Desktop Cube and @Neo-29 has the problem that the swipe gestures stop working after locking the screen. While both issues have not been present prior to GNOME 46, they seem to be pretty different to me.

**Comment by Schneegans** [comment]
@Slot2995 Did you restart your session between disabling all extensions and enabling the desktop cube? The correct procedure would be:

* Disable all extensions.
* Restart your session: Either logout / login or reboot your system.
* Enable only the Desktop Cube.

**To avoid any interference between extensions, it is necessary to start your session with either no or at most one extension enabled.**

Besides, have you changed any settings in the Desktop Cube? Maybe you could try resetting the preferences. And you should try this on both Wayland and X11 and see if it makes any difference.

**Comment by Slot2995** [comment]
I'm getting a little frustrated answering the same question over and over. Yes I disabled all the other extensions. Yes it is only the desktop cube and unless the settings somehow remain in place after the cube is uninstalled from the terminal and reinstalled then I didn't change the settings of it either. When I was using the cube before GNOME 46 I had changed some of the settings (added a background image I think was the only thing I changed) but I had to uninstall the cube from the terminal before I could turn the extensions on again

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by Schneegans** [comment]
For now, I cannot reproduce this issue on a fresh Fedora 40 installation - so it must be something more or less specific to your system. Debugging this from my side is pretty complicated! If you do not tell me _exactly_ what you did, I can only guess what's going on.

And I think that you did not really answer my questions.

* You did not write that you restarted your session between disabling all extensions and enabling the cube. However, this is extremely important! I get many bug reports from people thinking that just disabling all other extensions is sufficient to rule out any incompatibilities.
* Re-installing a GNOME Shell extension does not reset its settings. Please open the extension's settings (this is possible even with the extension disabled) and reset all toggles in there. Especially the background panorama if it's still set.
* Have you checked Wayland / X11?

**Comment by Slot2995** [comment]
I am using Wayland and Arch not Fedora.(IDK if your using a different os for a reason but...) But ya, I didn't just restart my session I restarted my system after turning off the other extensions sorry if I was not clear about that. and I can't even get to the settings because it kicks me out the second I install the cube. it very well could be specific to my setup or more likely still that I have set something up incorrectly somewhere else in my system that is causing issues I really dont know. IDK how much it matters either but the laptop I am using has been my linux project for almost a year. I have used A LOT of different OS's and configurations and whatever else I use has been tested on this laptop before making its way into the rest of my systems. that being said I use the cube any time I am running GNOME and never had any other issues with it so.....

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by Schneegans** [comment]
That's weird. Could you try resetting all Desktop-Cube preferences using `dconf-editor` as outlined [here](https://askubuntu.com/questions/1446822/how-do-i-reset-a-gnome-extensions-settings-to-default-ex-for-awesome-tiles)?

Does this change anything?

**Comment by Slot2995** [comment]
Hi, I think that I discovered a possible reason that this was happening to me. after trying to reinstall arch and digging around in my BIOS a little I figured out that my system clock was 2 hours off. IDK how or why but it was. anyway I know this can cause a lot of weird things to happen so I figured I would let you know...

Sent with [Proton Mail](https://proton.me/) secure email.
