### ISSUE TITLE
drag windows to adjacent workspaces is not working anymore

### ISSUE THREAD

**Issue by Sidethorn** [Schneegans/Desktop-Cube#166]
## Describe the Bug
drag windows to adjacent workspaces is not working anymore
Click on top bar and move window to border side

## Expected Behavior
Move dragged window to next workspace

## System
Arch
 - Desktop Cube version24 
 - GNOME Shell version: 46

**Comment by FelixFourcolor** [comment]
same here

**Comment by lusmo** [comment]
Yes, this great and very useful feature stopped working after upgrading to Fedora 40.

**Comment by SirBubbles** [comment]
I'd like to add my own experiences with this bug. I've had it for some time, only just noticed yesterday. I really came to like the feature of dragging windows to adjacent workspaces, and hope it gets fixed soon.
I'm on current Manjaro Stable.

**Comment by Schneegans** [comment]
Sorry for the late response here. I was very busy with [Kando](https://github.com/kando-menu/kando) recently and did not yet have a copy of GNOME 46 on real hardware :sweat: 

But I'll release a new version of the Desktop Cube ASAP which should fix the issue! Thanks for the report!

**Comment by FelixFourcolor** [comment]
it works, tysm!
