### ISSUE TITLE
Animated/video wallpaper

### ISSUE THREAD

**Issue by Tuxino88** [Schneegans/Desktop-Cube#17]
I hope I don't ask too much or bother. Would it be possible to implement in this extension or apart from the possibility of loading a video or a gif as a background?

**Comment by Schneegans** [comment]
Hey there! Do you mean the wallpaper which is shown on the cube's sides or the (usually gray) background behind the cube?

**Comment by Tuxino88** [comment]
I was thinking more about the desktop background. As you rightly pointed out to me in a previous request, perhaps it would be better as a separate extension

**Comment by Schneegans** [comment]
Yeah, I think this should be done in a separate extension. And there seem to be some existing attempts, [like this](https://github.com/Truemmerer/animated_wallpaper_helper), [this](https://github.com/ujjwal96/xwinwrap), or [this](https://github.com/chrisss404/gnome-shell-ext-VideoWallpaper). However, I never tried them and I do not know if any of those supports GNOME 40+ or Wayland... If not, someone should create a proper extension :wink:
