### ISSUE TITLE
Vertical Overview Support

### ISSUE THREAD

**Issue by Doomsdayrs** [Schneegans/Desktop-Cube#2]
## The Motivation
Users who use "Vertical Overview" will have a very wonky experience with windows (go test it yourself)

## The Solution
Support the cube being vertical

**Comment by Schneegans** [comment]
Thanks for the suggestion! 

This should be added. However, for me, other things will have a higher priority first. But if anybody volunteers in the meantime - it shouldn't be to hard to implement! This extension is still very small and easy to understand :smile:

**Comment by Schneegans** [comment]
The extension has become much more complex in the last months. I think that it's not so easy anymore to port this to a vertical layout (and a vertical cube looks pretty weird anyways, I guess). Please refer to #71 for any further comments.
