### ISSUE TITLE
Disable Cube when multi-monitor detected

### ISSUE THREAD

**Issue by quazardous** [Schneegans/Desktop-Cube#47]
## The Motivation
As many nomad users, I often plug and unplug my laptop from its dock.
At home with the dock, I use a multi-monitor layout.
With my layout the Cube is not very adequate.

## The Solution
Add a checkbox to disable the Cube when multi-monitor is detected.

## The Alternatives
I can disable it myself.

**Comment by Schneegans** [comment]
Hi there; thanks for the suggestion!

However, I would really want to try adding proper multi-monitor support before such a workaround. Until then, you can achieve what you want with a script, I guess. For example, [this](https://stackoverflow.com/questions/37236103/run-a-script-on-monitor-connection-disconnection-event) looks promising (although I did not try it). The commands for enabling or disabling the extension are as follows:

```bash
gnome-extensions enable desktop-cube@schneegans.github.com
```

```bash
gnome-extensions disable desktop-cube@schneegans.github.com
```
