### ISSUE TITLE
Also show 3d cube when switching workspaces in 'normal' mode

### ISSUE THREAD

**Issue by hklaufus** [Schneegans/Desktop-Cube#5]
## The Motivation
One can switch workspaces in 'normal' mode, i.e. outside the activities overview mode. 
The request is to enable 3D desktop cube when switching in normal mode.

## The Solution
Similar to desktop cube workspace switching in activities mode, rotate the workspaces using the desktop cube.
Possibly a small zoom out is required when pressing the \<CTRL>+\<ALT> keys to show the desktop on the face of the cube. The cube starts rotating when pressing the cursor left or right keys (while keeping the \<CTRL>+\<ALT> keys pressed).
Zoom in towards the face of the cube / show full desktop once \<CTRL>+\<ALT> keys are released.

## The Alternatives
None, keep as is.

**Comment by Schneegans** [comment]
Thanks for the suggestion! I will definitely try to implement this. In the current state, this "non-cuboid" transition breaks the illusion. However, it might be difficult (if not impossible) to get this right. I haven't look much into the respective GNOME Shell source code yet, but I think that this is implemented quite differently than the overview... I'll investigate :)

**Comment by SmilerOnline** [comment]
This is one of the main things that got me excited when I first heard about the extension.
I previously was jealous that KDE had this feature previously (although it was removed in a recent update) that allowed me to simply scroll the taskbar to switch workspaces and see the 3D animated cube effect.
I don't often use the overview mode to switch workspaces as I typically just scroll over Dash-to-Panel/Dock to switch workspaces quickly.
It would be great to eventually see that WS switch animation go from a 2D linear scroll to a 3D cube effect.
I certainly think some of my Mac/Windows friends will be more tempted to give Linux a try if they see the fancy animations (whether they are of any use in the real world I don't think it really matters, people often just get seduced by the visual beauty of the desktop when it looks good and are more tempted to give Linux a try just for the style alone).

I really hope that it is possible to achieve this in the extension eventually as I just simply want it to enable me to show Linux at its visual best to the non-Linux folks! :)

**Comment by Schneegans** [comment]
It's now implemented in the `main` branch and it will be released soonishly with the next update! If you want to test it, make sure to uncheck the "Unfold to Desktop" option!

**Comment by SmilerOnline** [comment]
Just tried it, it works nicely on my desktop!

The only thing that I was a little bit surprised by was that when I have one workspace in use and an empty workspace (two workspaces), I'd notice that the workspaces sit 180 degrees from each other so the other workspace would be facing away and have blank space between the two workspaces during animation.
Though with three workspaces, It behaved differently, with all of them connected at the edges and forming effectively a triangle shape with the edges touching one another.

I'm not sure if this was the expected outcome or not, but just wanted to share my experiences if it may help.

Great work and I really appreciate you taking the time to add this feature! :+1:

**Comment by Schneegans** [comment]
Yeah, this is the same as in overview mode. What kind of layout would you have expected in this case? Btw, it is different if you enable the gap between last and first workspace.

**Comment by hklaufus** [comment]
@Schneegans : Thanks for the great work, Simon!

**Comment by SmilerOnline** [comment]
> Yeah, this is the same as in overview mode. What kind of layout would you have expected in this case? Btw, it is different if you enable the gap between last and first workspace.

I'm just a little used to the KDE 3D cube that's all.
On KDE 3D Cube even with only two workspaces, there would be no gaps between workspaces, I just made the assumption that this extension was looking to recreate much of that same experience, which is the only reason I mentioned it.

Thanks again for the feature :)

**Comment by Schneegans** [comment]
To be honest, I never used the KDE cube. I wasn't even aware that one exists. I only used to use the Compiz one :-)

**Comment by SmilerOnline** [comment]
Yeah, no worries, I never used Compiz, I've not been on Linux for long enough...
KDE had the cube up until September 2021 as an option, but it's no longer available.
I'm just happy that when I have three workspaces open it has that 3D effect now :)
