### ISSUE TITLE
Dual monitor: window blinks with panoramic BG

### ISSUE THREAD

**Issue by quazardous** [Schneegans/Desktop-Cube#62]
## Describe the Bug
When using dual monitor AND panoramic background, the window on the non rotating monitor blinks (*).
(\*) blink = disappear/reappear

- Have a Dual monitor setting.
- Choose a nice panoramic
- do workspace switch

The window blinks !

## Expected Behavior
Smooth rotation.

## System
DC9
fedora 35

**Comment by Schneegans** [comment]
Hi there! Thanks for the report, I can actually reproduce the issue. I'll look into it!

**Comment by Schneegans** [comment]
I just pushed a fix to the `main` branch which should fix this issue. You can directly test it by installing the extension from the repo, or you wait for the next release on extensions.gnome.org! Thanks again for the report!

(feel free to post a comment here if the issue persists on your end)
