### ISSUE TITLE
 Turn off automatic rotation 

### ISSUE THREAD

**Issue by zhanshime** [Schneegans/Desktop-Cube#72]
Excellent extension, thank you.
 But there is a problem. When you drag a software to the edge of the screen, the screen will automatically flip to the next desktop. 
I don't think it should be, because the original function is that the software automatically occupies half of the screen. I hope it can provide the option to turn off automatic rotation.

**Comment by Schneegans** [comment]
You can disable this in the settings :wink: 

![image](https://user-images.githubusercontent.com/829942/168584798-004f77af-37d0-458f-a3d5-0a3993b62f48.png)

**Comment by zhanshime** [comment]
3q,i think the extension and dash to dock can integrate in gnome by default lol
one for efficient,one for just cool
