### ISSUE TITLE
Configure pressure to switch workspaces when dragging windows to edge

### ISSUE THREAD

**Issue by johns2s** [Schneegans/Desktop-Cube#82]
## The Motivation
I like the ability to switch workspaces by dragging windows to the edge, but I often find myself accidentally activating this when attempting to just move or tile a window.

## The Solution
If possible, it would be great to allow a configurable pressure threshold before the workspace switch is triggered

**Comment by Schneegans** [comment]
Thank you for this idea! It is now configurable in the latest `main` branch.
